apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-leader-election
  namespace: cert-manager
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-leader-election
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
- kind: ServiceAccount
  name: cert-manager-cainjector
  namespace: cert-manager
roleRef:
  kind: Role
  name: cert-manager-leader-election
  apiGroup: rbac.authorization.k8s.io